
FROM nginx:1.23.1-alpine

WORKDIR /usr/share/nginx/html

ADD . . 
# The difference between ADD and COPY is that ADD is used to add files into the image while COPY is used to copy files into the contaner.