version: "3.9"
services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - C:\Users\crisp\OneDrive\Documents\Node\node-backend\25_DOCKER\01_DOCKERIZING_NODEJS_APP:/app
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
