version: "3.6"
services:
  redisdb:
    container_name: redis_container
    image: redis:5.0.14-alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - internalnet
  flaskapp:
    container_name: flaskserver
    build: .
    image: flaskapp:1.0
    ports:
      - "3001:3001"
    expose:
      - "3001"
    depends_on:
      - redisdb
    networks:
      - internalnet
volumes:
  cache:
    driver: local

networks:
  internalnet:
    driver: bridge
