CREATE DATABASE IF NOT EXISTS todos;

USE todos;

DROP TABLE IF EXISTS todos;

CREATE TABLE todos (
  id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  title      VARCHAR(255) NOT NULL,
  completed  BIT NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
);