CREATE DATABASE todos;

USE todos;

CREATE TABLE todo(
    id BIGSERIAL NOT NULL,
    title VARCHAR(225) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(id)
)